name: argy
description: Manages command line arguments.
version: 1.0.0
repository: https://github.com/joegasewicz/argy

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
